name: Release Workflow


on:
 pull_request:
    types:
      - closed
    branches:
      - main

# secret 변수 write 허용      
permissions:
  contents: write

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Deploy
        run: |
          mkdir -p ./java-caller/deploy
          cp build/libs/*.jar ./java-caller/deploy

      - name: Display JAR contents
        run: unzip -l ./java-caller/deploy/*.jar
        if: success()

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Yarn
        run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
          echo 'export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"' >> "$HOME"/.bashrc
        shell: bash    

      - name: Release to npm
        uses: actions/setup-node@v3
        with:
          registry-url: "https://registry.npmjs.org"
      - run: |
          cd ./java-caller
          if [ -f "yarn.lock" ]; then
          yarn install
          else
          npm install
          fi
          git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
          git config --global user.name ${{ secrets.GIT_USER_NAME }}
          yarn shipjs trigger
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          JAVA_JAR_PATH: ${{ env.JAVA_JAR_PATH }}